# DECAPBRIDGE CONFIGURATION (Modern Authentication)
backend:
    name: decap-bridge
    repo: Rowee13/phs-nextjs-starter
    branch: cms-decap
    site_id: 49b7b6dd-3987-4ac7-951c-ac7efbd0a97e

    # Quickly see who did what (optional)
    commit_messages:
        create: Create {{collection}} "{{slug}}" - {{author-name}} <{{author-login}}> via DecapBridge
        update: Update {{collection}} "{{slug}}" - {{author-name}} <{{author-login}}> via DecapBridge
        delete: Delete {{collection}} "{{slug}}" - {{author-name}} <{{author-login}}> via DecapBridge
        uploadMedia: Upload "{{path}}" - {{author-name}} <{{author-login}}> via DecapBridge
        deleteMedia: Delete "{{path}}" - {{author-name}} <{{author-login}}> via DecapBridge
        openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

# FALLBACK CONFIGURATION (Netlify Identity - Deprecated but functional)
# backend:
#     name: git-gateway
#     branch: main

# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Enable local backend for development
local_backend: true

# Media storage
media_folder: 'public/uploads'
public_folder: '/uploads'

# Site settings - UPDATE THESE WITH YOUR ACTUAL NETLIFY URL
site_url: https://cms-decap-next-blog.netlify.app
display_url: https://cms-decap-next-blog.netlify.app
# logo_url: https://cms-decap-next-blog.netlify.app/logo.png

# Editorial workflow (optional)
publish_mode: editorial_workflow

# Show preview links
show_preview_links: true

# Collections define the structure for different content types
collections:
    - name: 'blog'
      label: 'Blog Posts'
      folder: 'content/posts'
      create: true
      slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
      preview_path: 'blog/{{slug}}'
      fields:
          - {
                label: 'Layout',
                name: 'layout',
                widget: 'hidden',
                default: 'blog',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - {
                label: 'Featured Image',
                name: 'thumbnail',
                widget: 'image',
                required: false,
            }
          - { label: 'Description', name: 'description', widget: 'text' }
          - {
                label: 'Author',
                name: 'author',
                widget: 'string',
                default: 'Admin',
            }
          - { label: 'Tags', name: 'tags', widget: 'list', default: ['blog'] }
          - { label: 'Body', name: 'body', widget: 'markdown' }

    - name: 'pages'
      label: 'Pages'
      files:
          - label: 'About'
            name: 'about'
            file: 'content/pages/about.md'
            preview_path: 'about'
            fields:
                - { label: 'Title', name: 'title', widget: 'string' }
                - { label: 'Body', name: 'body', widget: 'markdown' }
          - label: 'Contact'
            name: 'contact'
            file: 'content/pages/contact.md'
            preview_path: 'contact'
            fields:
                - { label: 'Title', name: 'title', widget: 'string' }
                - { label: 'Body', name: 'body', widget: 'markdown' }
